server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: never
  port: 8140

# spring
spring:
  config:
    activate:
      on-profile: default

  messages:
    basename: messages, errors

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Seoul

