server:
  port: 8140

spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
logging:
  level:
    com:
      recody: debug
    org:
      springframework:
        web: debug
        security: debug