name: build-test integration

on:
  push:
    paths-ignore: 
      - '.github/ISSUE_TEMPLATE/**'
      - 'README.md'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: load application envs
        run: |
          touch ./common/src/main/resources/env.dev.properties
          touch ./common/src/main/resources/env.test.properties
          touch ./common/src/main/resources/application-dev.yml

          echo "${{env.ENV_DEV_PROPERTIES}}" >> ./common/src/main/resources/env.dev.properties
          echo "${{env.ENV_TEST_PROPERTIES}}" >> ./common/src/main/resources/env.test.properties
          echo "${{env.APPLICATION_DEV_YML}}" >> ./common/src/main/resources/application-dev.yml
        shell: bash
        env:
          APPLICATION_DEV_YML: ${{secrets.APPLICATION_DEV_YML}}
          ENV_DEV_PROPERTIES: ${{secrets.ENV_DEV_PROPERTIES}}
          ENV_TEST_PROPERTIES: ${{secrets.ENV_TEST_PROPERTIES}}


      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: test Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Just Try Generate deployment package
        run: |
          mkdir -p deploy/build/libs
          cp build/libs/*.jar deploy/build/libs/
          cp Dockerfile deploy/Dockerfile
          cd deploy && zip -r deploy.zip .