name: build-test integration

on:
  push:
    branches: [ "develop" ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - 'README.md'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: load application envs
        run: |
          touch ./service-movie/impl/src/main/resources/env.dev.properties
          touch ./service-movie/impl/src/main/resources/application-dev.yml

          echo "${{env.ENV-DEV-PROPERTIES}}" >> ./service-movie/impl/src/main/resources/env.dev.properties
          echo "${{env.APPLICATION-DEV-YML}}" >> ./service-movie/impl/src/main/resources/application-dev.yml
        shell: bash
        env:
          APPLICATION-DEV-YML: ${{secrets.APPLICATION_DEV_YML}}
          ENV-DEV-PROPERTIES: ${{secrets.ENV_DEV_PROPERTIES}}


      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: test Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Generate deployment package
        run: |
          mkdir -p deploy/build/libs
          cp build/libs/*.jar deploy/build/libs/
          cp Dockerfile deploy/Dockerfile
          cd deploy && zip -r deploy.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.BEANSTALK_USER_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.BEANSTALK_USER_SECRET_KEY }}
          application_name: ${{ secrets.BEANSTALK_DEV_APPLICATION_NAME }}
          environment_name: ${{ secrets.BEANSTALK_DEV_ENVIRONMENT_NAME }}
          version_label: recody-backend-dev-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
